OnlineApp/OnlineApp/Models/Users.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OnlineApp.Models
{
    public class Users
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required(ErrorMessage = "please enter  id")]
        public int UserId { get; set; }

        [Required(ErrorMessage = "please enter  name")]
        [StringLength(10, MinimumLength = 3)]
        public string UserName { get; set; }



        [Required(ErrorMessage = "please enter  password")]
        [StringLength(10, MinimumLength = 5)]
        public string UserPassword { get; set; }
    }
}

OnlineApp/OnlineApp/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineApp.Migrations;
using OnlineApp.Models;

namespace OnlineApp.Controllers
{
    public class CourseController : Controller
    {
        // GET: Course
        
        private UserContext _context;
        public CourseController()
        {
            this._context = new UserContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        public ActionResult ViewCourse()
        {
            return View(_context.Courses.ToList());
        }
        
        public ActionResult SelectCourse(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            Course course = _context.Courses.Find(id);
            if(course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }
        

        [HttpPost]
        public ActionResult SelectCourse(Course course)
        {
            
            if (ModelState.IsValid)
            {
                using (UserContext db = new UserContext())
                {
                    
                    CourseDetails cod = new CourseDetails();
                    cod.UsId = Convert.ToInt16(Session["UserId"]);
                    cod.CoId = course.CourseId;
                    cod.CoName = course.CourseName;
                    cod.CoDept = course.CourseDept;
                    db.CourseDetails.Add(cod);
                    db.SaveChanges();
                    ViewBag.Message = " sucessfully registered";
                }
 
                ModelState.Clear();
                
            }
            
            return View(course);
        }
        
        public ActionResult Pay(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            Course course = _context.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            ViewBag.Message = " sucessfully Paid";
            return View(course);
        }
        public ActionResult SchedDate(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            Course course = _context.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }
        [HttpPost]
        public ActionResult SchedDate(Course course,string ScheduleDate)
        {

            if (ModelState.IsValid)
            {
                using (UserContext db = new UserContext())
                {
                    DateTime Val = Convert.ToDateTime(ScheduleDate);
                    PayDetail pd = new PayDetail();
                    pd.Uid = Convert.ToInt16(Session["UserId"]);
                    pd.Cid = course.CourseId;
                    pd.Status= "Paid";
                    pd.ScheduleDate=Val; 
                    db.PayDetails.Add(pd);
                    db.SaveChanges();
                    ViewBag.Message = " sucessfully Scheduled";
                }

                ModelState.Clear();

            }
            return View();
        }
        public ActionResult ViewUrCourse()
        {
            using (UserContext db = new UserContext())
            {
                int id = Convert.ToInt16(Session["UserId"]);
                var crs = db.CourseDetails.SingleOrDefault(u => u.UsId == id );
                if (crs != null)
                {
                    return View();

                }
                else
                {
                    ModelState.AddModelError("", "No registered Courses.");
                }
            }
            return View();
        }

    }
    }

OnlineApp/OnlineApp/Controllers/UserController.cs
using Antlr.Runtime.Misc;
using OnlineApp.Models;
using System;
using System.Configuration;
using System.Data.Entity.Core.Common.CommandTrees;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;


namespace OnlineApp.Controllers
{
    public class UserController : Controller
    {
        private UserContext _context;

        // GET: User
        public UserController()
        {
            this._context = new UserContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        public ActionResult Index()
        {
            return View(_context.Users.ToList());
        }
        public ActionResult ViewUsers()
        {
            return View(_context.Users.ToList());
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            Users us = _context.Users.Find(id);
            if (us == null)
            {
                return HttpNotFound();
            }
            return View(us);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            Users us = _context.Users.Find(id);
            _context.Users.Remove(us);
            _context.SaveChanges();
            return RedirectToAction("ViewUsers");
        }
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(Users obj)
        {
            if (ModelState.IsValid)
            {
                using (UserContext db = new UserContext())
                {
                    db.Users.Add(obj);
                    db.SaveChanges();
                }
                ModelState.Clear();
                ViewBag.Message = obj.UserName + " " + " sucessfully registered.";
            }
            return View();
        }


        public ActionResult Login()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Login(Users user)
        {
            using (UserContext db = new UserContext())
            {
                var usr = db.Users.SingleOrDefault(u => u.UserName == user.UserName && u.UserPassword == user.UserPassword);
                if (usr != null)
                {
                    Session["UserId"] = usr.UserId.ToString();
                    Session["UserName"] = usr.UserName.ToString();
                    return RedirectToAction("LoggedIn");
                }
                else
                {
                    ModelState.AddModelError("", "UserName or Password is wrong.");
                }
            }
            return View();
        }

        public ActionResult LoggedIn()
        {
            if (Session["UserId"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login");
            }
        }
    }
}

OnlineApp/OnlineApp/Views/User/Delete.cshtml
<!DOCTYPE html>
<html>
<body>
    @model OnlineApp.Models.Users

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>User</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.UserId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UserId)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.UserName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UserName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.UserPassword)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UserPassword)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "LoggedIn", "User")
            </div>
        }
    </div>
    <style>
        body {
            background-image: url('https://www.theselfemployed.com/wp-content/uploads/2016/09/ecommerce-sales.jpg');
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: 100% 100%;
            opacity: 1.5;
            text-align: center;
            color: black;
            font-weight: bolder;
        }
        input[type=submit] {
            background-color: white;
            border: 2px solid darkcyan;
            color: black;
            padding: 16px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            transition-duration: 0.4s;
            cursor: pointer;
            font-family: cursive;
        }

            input[type=submit]:hover {
                background-color: darkcyan;
                color: black;
            }
    </style>
</body>
</html>

OnlineApp/OnlineApp/Views/User/Index.cshtml
<!DOCTYPE html>
<html>
<body>
    @model IEnumerable<OnlineApp.Models.Users>
    @{
        ViewBag.Title = "Index";
    }

    <h2>Index</h2>
    <p>
        @Html.ActionLink("Create New", "Register")
    </p>



    <table class="table">
        <tr>
            <th>

                @Html.DisplayNameFor(Users => Users.UserId)
            </th>

            <th>

                @Html.DisplayNameFor(Users => Users.UserName)
            </th>

        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(m => item.UserId)
                </td>

                <td>
                    @Html.DisplayFor(m => item.UserName)
                </td>
            </tr>

        }
    </table>
    
    <style>
        body {
            background-image: url('https://www.theselfemployed.com/wp-content/uploads/2016/09/ecommerce-sales.jpg');
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: 100% 100%;
            opacity: 1.5;
            text-align: center;
            color: black;
            font-weight: bolder;
        }

        table {
            border-collapse: collapse;
            width: 100%;
        }

        th {
            text-align: left;
            padding: 8px;
            background-color: mediumseagreen;
            color: white;
        }

        tr:nth-child(even) {
            background-color: lightseagreen ;
            color: black;
        }

        tr:nth-child(odd) {
            background-color: white;
            color: black;
        }
    </style>
</body>
</html>

OnlineApp/OnlineApp/Views/User/LoggedIn.cshtml
<!DOCTYPE html>
<html>
<body>
    @{
        ViewBag.Title = "LoggedIn";
    }

    @if (Session["UserId"] != null)
    {
        <h4>Hello @Session["UserName"].ToString()</h4>
        @Html.ActionLink("View Course", "ViewCourse", "Course")
        <br>
        @Html.ActionLink("View your Courses", "ViewUrCourse", "Course")
        <br>
    }
    <div>
        @Html.ActionLink("Logoff", "Login", "User", new { Style = "color:Red" })
    </div>
    <style>
        body {
            background-image: url('https://www.theselfemployed.com/wp-content/uploads/2016/09/ecommerce-sales.jpg');
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: 100% 100%;
            opacity: 1.5;
            text-align: center;
            color: black;
            font-weight: bolder;
        }
    </style>
</body>
</html>

OnlineApp/OnlineApp/Views/User/Login.cshtml
<!DOCTYPE html>
<html>
<body>
    @model OnlineApp.Models.Users

    @{
        ViewBag.Title = "Login";
    }

    <h2>Login</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>User</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.UserPassword, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.PasswordFor(model => model.UserPassword, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserPassword, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Login" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
    
    <style>
        body {
            background-image: url('https://www.theselfemployed.com/wp-content/uploads/2016/09/ecommerce-sales.jpg');
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: 100% 100%;
            opacity: 1.5;
            text-align: center;
            color: black;
            font-weight: bolder;
        }
        div {
            text-align: center;
            color: black;
        }

        input[type=submit] {
            background-color: white;
            border: 2px solid darkcyan;
            color: black;
            padding: 16px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            transition-duration: 0.4s;
            cursor: pointer;
            font-family: cursive;
        }

            input[type=submit]:hover {
                background-color: darkcyan;
                color: black;
            }
    </style>
</body>
</html>

OnlineApp/OnlineApp/Views/User/Register.cshtml
<!DOCTYPE html>
<html>
<body>
    @model OnlineApp.Models.Users

    @{
        ViewBag.Title = "Register";
    }

    <h2>Register</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>User</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @if (ViewBag.Message != null)
            {
                <div class="form-group">
                    <div class="col-md-10">@ViewBag.Message</div>
                </div>
            }
            <div class="form-group">
                @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UserPassword, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UserPassword, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserPassword, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Register" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
    <style>
        body {
            background-image: url('https://www.theselfemployed.com/wp-content/uploads/2016/09/ecommerce-sales.jpg');
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: 100% 100%;
            opacity: 1.5;
            text-align: center;
            color: black;
            font-weight: bolder;
        }

        input[type=submit] {
            background-color: white;
            border: 2px solid darkcyan;
            color: black;
            padding: 16px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            transition-duration: 0.4s;
            cursor: pointer;
            font-family: cursive;
        }

            input[type=submit]:hover {
                background-color: darkcyan;
                color: black;
            }
    </style>
</body>
</html>

OnlineApp/OnlineApp/Views/User/ViewUsers.cshtml
<!DOCTYPE html>
<html>
<body>
    @model IEnumerable<OnlineApp.Models.Users>

    @{
        ViewBag.Title = "ViewUsers";
    }

    <h2>View Users</h2>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(Users => Users.UserId)
            </th>
            <th>
                @Html.DisplayNameFor(Users => Users.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(Users => Users.UserPassword)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(m => item.UserId)
                </td>
                <td>
                    @Html.DisplayFor(m => item.UserName)
                </td>
                <td>
                    @Html.DisplayFor(m => item.UserPassword)
                </td>
                <td>
                    @Html.ActionLink("Delete User", "Delete", new { id = item.UserId })
                </td>

            </tr>
        }
        <div>
            @Html.ActionLink("Back to List", "ViewAdminCourses")
        </div>
    </table>
    <style>
        body {
            background-image: url('https://www.theselfemployed.com/wp-content/uploads/2016/09/ecommerce-sales.jpg');
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: 100% 100%;
            opacity: 1.5;
            text-align: center;
            color: black;
            font-weight: bolder;
        }

        table {
            border-collapse: collapse;
            width: 100%;
           
        }

        th {
            text-align: left;
            padding: 8px;
            background-color: mediumseagreen;
            color: white;
        }

        tr:nth-child(even) {
            background-color: lightseagreen;
            color: black;
        }

        tr:nth-child(odd) {
            background-color: white;
            color: black;
        }
    </style>
</body>
</html>