OnlineApp/OnlineApp/Controllers/QRCodeGeneratorController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineApp.Models;
using ZXing;

namespace OnlineApp.Controllers
{
    public class QRCodeGeneratorController : Controller
    {
        // GET: QRCodeGenerator
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Generate(QRCodeModel qrcode)
        {
            try
            {
                qrcode.QRCodeImagePath = GenerateQRCode(qrcode.QRCodeText);
                ViewBag.Message = "QR Code Created successfully";
            }
            catch (Exception ex)
            {
                //catch exception if there is any
            }
            return View("Index", qrcode);
        }

        private string GenerateQRCode(string qrcodeText)
        {
            string folderPath = "~/Images/";
            string imagePath = "~/Images/QrCode.jpg";
            // If the directory doesn't exist then create it.
            if (!Directory.Exists(Server.MapPath(folderPath)))
            {
                Directory.CreateDirectory(Server.MapPath(folderPath));
            }

            var barcodeWriter = new BarcodeWriter();
            barcodeWriter.Format = BarcodeFormat.QR_CODE;
            var result = barcodeWriter.Write(qrcodeText);

            string barcodePath = Server.MapPath(imagePath);
            var barcodeBitmap = new Bitmap(result);
            using (MemoryStream memory = new MemoryStream())
            {
                using (FileStream fs = new FileStream(barcodePath, FileMode.Create, FileAccess.ReadWrite))
                {
                    barcodeBitmap.Save(memory, ImageFormat.Jpeg);
                    byte[] bytes = memory.ToArray();
                    fs.Write(bytes, 0, bytes.Length);
                }
            }
            return imagePath;
        }

        public ActionResult Read()
        {
            return View(ReadQRCode());
        }

        private QRCodeModel ReadQRCode()
        {
            QRCodeModel barcodeModel = new QRCodeModel();
            string barcodeText = "";
            string imagePath = "~/Images/QrCode.jpg";
            string barcodePath = Server.MapPath(imagePath);
            var barcodeReader = new BarcodeReader();

            var result = barcodeReader.Decode(new Bitmap(barcodePath));
            if (result != null)
            {
                barcodeText = result.Text;
            }
            return new QRCodeModel() { QRCodeText = barcodeText, QRCodeImagePath = imagePath };
        }
    }
}

OnlineApp/OnlineApp/Controllers/UserController.cs
using Antlr.Runtime.Misc;
using OnlineApp.Models;
using System;
using System.Configuration;
using System.Data.Entity.Core.Common.CommandTrees;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;


namespace OnlineApp.Controllers
{
    public class UserController : Controller
    {
        private UserContext _context;

        // GET: User
        public UserController()
        {
            this._context = new UserContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        public ActionResult Index()
        {
            return View(_context.Users.ToList());
        }
        public ActionResult ViewUsers()
        {
            return View(_context.Users.ToList());
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            Users us = _context.Users.Find(id);
            if (us == null)
            {
                return HttpNotFound();
            }
            return View(us);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            Users us = _context.Users.Find(id);
            _context.Users.Remove(us);
            _context.SaveChanges();
            return RedirectToAction("ViewUsers");
        }
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(Users obj)
        {
            if (ModelState.IsValid)
            {
                using (UserContext db = new UserContext())
                {
                    db.Users.Add(obj);
                    db.SaveChanges();
                }
                ModelState.Clear();
                ViewBag.Message = obj.UserName + " " + " sucessfully registered.";
            }
            return View();
        }


        public ActionResult Login()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Login(Users user)
        {
            using (UserContext db = new UserContext())
            {
                var usr = db.Users.SingleOrDefault(u => u.UserName == user.UserName && u.UserPassword == user.UserPassword);
                if (usr != null)
                {
                    Session["UserId"] = usr.UserId.ToString();
                    Session["UserName"] = usr.UserName.ToString();
                    return RedirectToAction("LoggedIn");
                }
                else
                {
                    ModelState.AddModelError("", "UserName or Password is wrong.");
                }
            }
            return View();
        }

        public ActionResult LoggedIn()
        {
            if (Session["UserId"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login");
            }
        }
    }
}

OnlineApp/OnlineApp/Views/QRCodeGenerator/Index.cshtml
@model  OnlineApp.Models.QRCodeModel

@{
    ViewBag.Title = "Generate QR COde";
}

<h2>Generate QRCode</h2>


@using (Html.BeginForm("Generate", "QRCodeGenerator", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <span style="color:red; ">@ViewBag.Message </span>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.QRCodeText, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QRCodeText, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.QRCodeText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QRCodeImagePath, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if (Model != null && !String.IsNullOrEmpty(Model.QRCodeImagePath))
                {
                    <img src="@Url.Content(Model.QRCodeImagePath)" alt="Image" />
                }

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Generate QR" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Read QR Code", "Read")
</div>

@section scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

}

OnlineApp/OnlineApp/Views/QRCodeGenerator/Read.cshtml
@model  OnlineApp.Models.QRCodeModel

@{
    ViewBag.Title = "Generate QR COde";
}

<h2>Generate QRCode</h2>


@using (Html.BeginForm("Generate", "QRCodeGenerator", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <span style="color:red; ">@ViewBag.Message </span>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.QRCodeText, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QRCodeText, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.QRCodeText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QRCodeImagePath, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if (Model != null && !String.IsNullOrEmpty(Model.QRCodeImagePath))
                {
                    <img src="@Url.Content(Model.QRCodeImagePath)" alt="Image" />
                }

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Generate QR" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Read QR Code", "Read")
</div>
<div>
    @Html.ActionLink("Logoff", "Login", "User")
</div>

@section scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

}